export const DUMMY_DATA = [
  {
    id: 1,
    title: '팀 스피노 프로젝트 2차 스크럼',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#e5565e',
    target: {
      time: '09 : 00',
      local: 'Seoul',
      day: '2022-05-04',
    },
    cur: {
      time: '19 : 00',
      local: 'London',
      day: '2022-05-05',
    },
    dayOfWeek: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 2,
    title: '카카오 개발자 미팅',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#FBE864',
    target: {
      time: '18 : 00',
      local: 'New York',
      day: '2022-05-03',
    },
    cur: {
      time: '9 : 00',
      local: 'London',
      day: '2022-05-03',
    },
    dayOfWeek: ['Tue', 'Wed', 'Fri', 'Sat'],
  },
  {
    id: 3,
    title: 'FaceBook 압둘 자바 미팅',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#5FA3F8',
    target: {
      time: '19 : 00',
      local: 'San Francisco',
      day: '2022-05-04',
    },
    cur: {
      time: '10 : 00',
      local: 'London',
      day: '2022-05-03',
    },
    dayOfWeek: ['Tue', 'Fri', 'Sat'],
  },
  {
    id: 4,
    title: 'Apple 스티브 잡스와의 미팅',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#F5BE5B',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-05',
    },
    cur: {
      time: '10 : 00',
      local: 'London',
      day: '2022-05-04',
    },
    dayOfWeek: ['Sat'],
  },
  {
    id: 5,
    title: '아마존 제프 베이조스와의 미팅 2일',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Seattle',
      day: '2022-05-02',
    },
    cur: {
      time: '08 : 00',
      local: 'London',
      day: '2022-05-02',
    },
    dayOfWeek: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 6,
    title: '테슬라 도지코인 시위',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-04',
    },
    cur: {
      time: '08 : 00',
      local: 'London',
      day: '2022-05-04',
    },
    dayOfWeek: ['Sun', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 6,
    title: '테슬라 도지코인 시위',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-04',
    },
    cur: {
      time: '08 : 00',
      local: 'London',
      day: '2022-05-04',
    },
    dayOfWeek: ['Sun', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 6,
    title: '테슬라 도지코인 시위',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-04',
    },
    cur: {
      time: '08 : 00',
      local: 'London',
      day: '2022-05-04',
    },
    dayOfWeek: ['Sun', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 6,
    title: '테슬라 도지코인 시위',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-04',
    },
    cur: {
      time: '08 : 00',
      local: 'London',
      day: '2022-05-04',
    },
    dayOfWeek: ['Sun', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 6,
    title: '테슬라 도지코인 시위',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-04',
    },
    cur: {
      time: '08 : 00',
      local: 'London',
      day: '2022-05-04',
    },
    dayOfWeek: ['Sun', 'Thu', 'Fri', 'Sat'],
  },
  {
    id: 7,
    title: '팀 브라키오 회의',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto officia nam exercitationem iure illum cupiditate minus numquam quibusdam nobis adipisci dolor, repellat quisquam iste sunt dignissimos ab praesentium possimus at.',
    tagColor: '#CB88F8',
    target: {
      time: '10 : 00',
      local: 'Los Angeles',
      day: '2022-05-09',
    },
    cur: {
      time: '18 : 00',
      local: 'London',
      day: '2022-05-09',
    },
    dayOfWeek: ['Sun', 'Thu', 'Fri', 'Sat'],
  },
];

export const DUMMY_DATA_CITY = [
  { id: 0, city: 'Pacific/Midway' },
  { id: 1, city: 'Pacific/Niue' },
  { id: 2, city: 'America/Anchorage' },
  { id: 3, city: 'America/Juneau' },
  { id: 4, city: 'America/Yakutat' },
  { id: 5, city: 'America/Nome' },
  { id: 6, city: 'America/Adak' },
  { id: 7, city: 'America/Metlakatla' },
  { id: 8, city: 'Pacific/Honolulu' },
  { id: 9, city: 'Pacific/Rarotonga' },
  { id: 10, city: 'Pacific/Tahiti' },
  { id: 11, city: 'Pacific/Marquesas' },
  { id: 12, city: 'America/Los_Angeles' },
  { id: 13, city: 'America/Vancouver' },
  { id: 14, city: 'America/Whitehorse' },
  { id: 15, city: 'America/Dawson' },
  { id: 16, city: 'America/Belize' },
  { id: 17, city: 'Africa/Cairo' },
  { id: 18, city: 'Africa/Harare' },
  { id: 19, city: 'Africa/Johannesburg' },
  { id: 20, city: 'Europe/Moscow' },
  { id: 21, city: 'Europe/Volgograd' },
  { id: 22, city: 'Europe/Kirov' },
  { id: 23, city: 'Europe/Astrakhan' },
  { id: 24, city: 'Europe/Saratov' },
  { id: 25, city: 'Europe/Ulyanovsk' },
  { id: 26, city: 'Europe/Samara' },
  { id: 27, city: 'Asia/Yekaterinburg' },
  { id: 28, city: 'Asia/Omsk' },
  { id: 29, city: 'Asia/Novosibirsk' },
  { id: 30, city: 'Asia/Barnaul' },
  { id: 31, city: 'Asia/Tomsk' },
  { id: 32, city: 'Asia/Novokuznetsk' },
  { id: 33, city: 'Asia/Krasnoyarsk' },
  { id: 34, city: 'Asia/Irkutsk' },
  { id: 35, city: 'Asia/Chita' },
  { id: 36, city: 'Asia/Yakutsk' },
  { id: 37, city: 'Asia/Khandyga' },
  { id: 38, city: 'Asia/Vladivostok' },
  { id: 39, city: 'Asia/Ust-Nera' },
  { id: 40, city: 'Asia/Magadan' },
  { id: 41, city: 'Asia/Sakhalin' },
  { id: 42, city: 'Asia/Srednekolymsk' },
  { id: 43, city: 'Asia/Kamchatka' },
  { id: 44, city: 'Asia/Anadyr' },
  { id: 45, city: 'Europe/Belgrade' },
  { id: 46, city: 'Europe/Bratislava' },
  { id: 47, city: 'Europe/Budapest' },
  { id: 48, city: 'Europe/Ljubljana' },
  { id: 49, city: 'Europe/Prague' },
  { id: 50, city: 'Europe/Sarajevo' },
  { id: 51, city: 'Europe/Skopje' },
  { id: 52, city: 'Europe/Warsaw' },
  { id: 53, city: 'Europe/Zagreb' },
  { id: 54, city: 'Europe/Brussels' },
  { id: 55, city: 'Europe/Copenhagen' },
  { id: 56, city: 'Asia/Tokyo' },
];
